-- Création de la table NPC
CREATE TABLE IF NOT EXISTS "NPC" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "race" TEXT NOT NULL,
    "class" TEXT,
    "level" INTEGER NOT NULL DEFAULT 1,
    "age" TEXT,
    "appearance" TEXT,
    "personality" TEXT,
    "ideals" TEXT,
    "bonds" TEXT,
    "flaws" TEXT,
    "background" TEXT,
    "occupation" TEXT,
    "location" TEXT,
    "stats" TEXT,
    "faction" TEXT,
    "allies" TEXT,
    "enemies" TEXT,
    "quirks" TEXT,
    "voice" TEXT,
    "goals" TEXT,
    "isImportant" BOOLEAN NOT NULL DEFAULT 0,
    "isAlive" BOOLEAN NOT NULL DEFAULT 1,
    "notes" TEXT,
    "imageUrl" TEXT,
    "authorId" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "NPC_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);